#!/usr/bin/env bash
# -*- coding: utf-8 -*-
set -x

#
# Docker build calls this script to harden the image during build.
#
# NOTE: To build on CircleCI, you must take care to keep the `find`
# command out of the /proc filesystem to avoid errors like:
#
#    find: /proc/tty/driver: Permission denied
#    lxc-start: The container failed to start.
#    lxc-start: Additional information can be obtained by \
#        setting the --logfile and --logpriority options.

adduser --shell /bin/sh --uid 1000 user
sed -i -r 's/^user:!:/user:x:/' /etc/shadow

# Be informative after successful login.
echo -e "\\n\\nBase Image built on $(date)." > /etc/motd

# Remove existing crontabs, if any.
rm -fr /var/spool/cron
rm -fr /etc/crontabs
rm -fr /etc/periodic

# Remove world-writable permissions.
find / -xdev -type d -perm /0002 -exec chmod o-w {} +
find / -xdev -type f -perm /0002 -exec chmod o-w {} +

# Assign write Access for all to tmp
chmod 1777 /tmp

# Remove all but a handful of admin commands.
find /sbin /usr/sbin -not -type d \
  -and -not -name nologin \
  -and -not -name setup-proxy \
  -and -not -name runit \
  -and -not -name runit-init \
  -delete

# Remove unnecessary user accounts.
sed -i -r '/^(user|root|_apt)/!d' /etc/group
sed -i -r '/^(user|root|_apt)/!d' /etc/passwd

# Remove interactive login shell for everybody but user.
sed -i -r '/^user:/! s#^(.*):[^:]*$#\1:/sbin/nologin#' /etc/passwd

sysdirs="
  /bin
  /etc
  /lib
  /sbin
  /usr
"

# Remove crufty...
#   /etc/shadow-
#   /etc/passwd-
#   /etc/group-
find $sysdirs -xdev -type f -regex '.*-$' -exec rm -f {} +

# Ensure system dirs are owned by root and not writable by anybody else.
find $sysdirs -xdev -type d \
  -exec chown root:root {} \; \
  -exec chmod 0755 {} \;

# Remove all suid files.
find $sysdirs -xdev -type f -and -perm /4000 -delete

# Remove other programs that could be dangerous.
find $sysdirs -xdev \( \
  -name hexdump -or \
  -name chgrp -or \
  -name chown -or \
  -name ln -or \
  -name od -or \
  -name strings -or \
  -name su \
  \) -delete

# Remove init scripts since we do not use them.
rm -fr /etc/init.d
rm -fr /lib/rc
rm -fr /etc/conf.d
rm -fr /etc/inittab
rm -fr /etc/runlevels
rm -fr /etc/rc.conf

# Remove kernel tunables since we do not need them.
rm -fr /etc/sysctl*
rm -fr /etc/modprobe.d
rm -fr /etc/modules
rm -fr /etc/mdev.conf
rm -fr /etc/acpi

# Remove root homedir since we do not need it.
rm -fr /root

# Remove fstab since we do not need it.
rm -f /etc/fstab

# Remove broken symlinks (because we removed the targets above).
find $sysdirs -xdev -type l -exec test ! -e {} \; -delete
